In [2]:
def selamla(isim):
    print("Merhaba",isim)
    return
isim= input("isim giriniz")
selamla(isim)

Merhaba ali


In [2]:
def büyük_bul(x,y,z):
    eb=x
    if y>eb:
        eb=y
    if z>eb:
        eb=z
    return eb
sayi1=5
sayi2=14
sayi3=8

eb=büyük_bul(sayi1,sayi2,sayi3)
print("en büyük sayı {}".format(eb))


en büyük sayı 14


In [4]:
def max_bul(listem):
    eb=-1
    for i in range(len(listem)):
        if listem[i]>eb:
            eb=listem[i]
    return eb

sayilar=[3,5,8,21,34,12,2]
max=max_bul(sayilar)
print("en büyük sayı {}".format(max))

en büyük sayı 34


In [5]:
def selamla(*kisiler):
    for k in kisiler:
        print(k," Merhaba")

selamla("Ali","Ahmet","3",5)

Ali  Merhaba
Ahmet  Merhaba
3  Merhaba
5  Merhaba


In [10]:
def toplama(*a):
    t=0
    for n in a:
        t=t+n
    return t

print(toplama(10,20,50,60))


140


In [12]:
def yazdir(**kwargs):
    for k in kwargs.items():
        print(k)
yazdir(pi=3.14,e=2.78) 

('pi', 3.14)
('e', 2.78)


In [14]:
def faktoriyel(n):
    if n==1:
        return n
    else:
        return n*faktoriyel(n-1)

print(faktoriyel(4))
    

24


In [15]:
us=lambda x,y:x**y
sonuc= us(4,5)
print(sonuc)

1024


In [17]:
kare=lambda x:x**2
sayılar=[1,7,6,3]
sonuc=map(kare,sayılar)
print("sayılar",sayılar)
print("kareleri",list(sonuc))

sayılar [1, 7, 6, 3]
kareleri [1, 49, 36, 9]


In [18]:
kisiler=['ali','ahmet','veli','emin']
tarihler=[2018,2022,2023,2020]
listem=list( 
    filter(
        lambda zipped: 2018<=zipped[1]<=2020, zip(kisiler,tarihler)
    ) 
    )
print(listem)

[('ali', 2018), ('emin', 2020)]


In [19]:
from functools import reduce


sayilar= [12,4,5,7]
çarpım=reduce(lambda x,y:x*y,sayilar)
print(çarpım)

1680


In [22]:
def Kelimebirleştir(kelime1,kelime2):
    kelime1up=kelime1.upper()
    kelime2up=kelime2.upper()
    print(kelime1up,kelime2up)
        

kelime1="Sokakta Sayamam gibi"
kelime2="Fıştıkçı Şahap"
Kelimebirleştir(kelime1,kelime2)


SOKAKTA SAYAMAM GIBI FIŞTIKÇI ŞAHAP


In [6]:
import re
def TemizleveSay(kelime):
    print (kelime)
    temiz=re.sub("[$@&.,\")('%:;?]","",kelime)
    print (temiz)
    kelimesayısı=temiz.split()

    print (len(temiz))
    print (len(kelimesayısı))


kelime1='Soka??kta, Saya%mam gibi:'
TemizleveSay(kelime1)



Soka??kta, Saya%mam gibi:
Sokakta Sayamam gibi
20
3


Numpy
terminalden python -m pip install matplotlib   ile yüklendi.
https://code.visualstudio.com/docs/python/python-tutorial   
"Install and use packages"  başlığı

In [34]:
import numpy as np
python_list=[0,1,2,3,4,5,6,7,8,9]
numpy_array = np.array([0,1,2,3,4,5,6,7,8,9])
numpy_Array2=np.array([[0,1,2,3,4,5,6,7,8,9]])
print("Ptyhon list:")
print(python_list)
print("numpy list:")
print(numpy_array)
print("***********************")
print(numpy_array.ndim)
print(numpy_Array2.ndim)
print("///////////////////////")
print(numpy_array.shape)
print(numpy_Array2.shape)

Ptyhon list:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
numpy list:
[0 1 2 3 4 5 6 7 8 9]
***********************
1
2
///////////////////////
(10,)
(1, 10)


In [32]:
import numpy as np
numpy_array = np.array([0,1,2,3,4,5,6,7,8,9])
reshape52=numpy_array.reshape(5,2)
print(reshape52)
reshape25=numpy_array.reshape(2,5)
print(reshape25)
print("________________________")
print(np.arange(0,10,3))
print(np.arange(10))
print(np.arange(0,10,1))
print(".......................")
print(reshape52[1])
print(reshape52[:,0])
print(reshape52[:,0:2])
print("***********************")
print(reshape52[::-1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
________________________
[0 3 6 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
.......................
[2 3]
[0 2 4 6 8]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
***********************
[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]


In [41]:
import numpy as np
print(np.zeros((2,3)))
print("________________________")
print(np.ones((2,3,4)))
print("________________________")
print(np.eye((3)))

[[0. 0. 0.]
 [0. 0. 0.]]
________________________
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
________________________
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
import numpy as np
numpy_array = np.array([0,1,2,3,4,5])
reshape32=numpy_array.reshape(3,2)
print(np.concatenate([reshape52,reshape52],axis=0))
print(np.concatenate([reshape52,reshape52],axis=1))
print("________________________")
print(numpy_array.mean())
print(numpy_array.var())
print(numpy_array.std())
print(np.median(numpy_array))


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]
 [8 9 8 9]]
________________________
2.5
2.9166666666666665
1.707825127659933
2.5


In [62]:
import numpy as np
numpy_array = np.array([1,2,3,4,5,6])
reshape32=numpy_array.reshape(3,2)
reshape23=numpy_array.reshape(2,3)
print(reshape32)
print("________________________")
print(reshape32+(reshape32+2))
print(reshape32-reshape32)
print(reshape32*reshape32)
print(reshape32/reshape32)
print("________________________")
print(np.dot(reshape32,reshape23))


[[1 2]
 [3 4]
 [5 6]]
________________________
[[ 4  6]
 [ 8 10]
 [12 14]]
[[0 0]
 [0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]
 [25 36]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
________________________
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [63]:
import numpy as np
numpy_array = np.array([1,2,3,4,5,6])
reshape32=numpy_array.reshape(3,2)
print(reshape32)
print(reshape32.T)


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [68]:
import numpy as np
numpy_array = np.array([1,2,3,4,5,6])
boolean_array=numpy_array>3
print(boolean_array)
print(numpy_array[boolean_array])

[False False False  True  True  True]
[4 5 6]
